# .github/workflows/main.yml

name: Python CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4 # Checks out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: '3.10' # Specify Python version compatible with your project

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        pytest test_vt_hash_checker.py # Execute your pytest tests
